/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    MapPmTiles: typeof import('./src/components/MapPmTiles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TutorialCard: typeof import('./src/components/TutorialCard.vue')['default']
    TutorialPmTilesCard: typeof import('./src/components/TutorialPmTilesCard.vue')['default']
  }
}
